# Generated by Django 5.2.4 on 2025-09-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phon_number', models.IntegerField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
